{% set name = "ndcsv" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/n/ndcsv/ndcsv-{{ version }}.tar.gz
  sha256: 6547a0d5b11c5addea20500173f1f4f3dc67882fe80c7e8829a5e6a0ba925a7f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - numpy >=1.23
    - pandas >=1.5
    - pshell >=1.0
    - xarray >=2023.8.0

test:
  imports:
    - ndcsv
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/crusaderky/ndcsv
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: N-Dimensional CSV files for xarray

extra:
  recipe-maintainers:
    - crusaderky
